remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Machine Learning and Artificial Intelligence Course and Projects
description: All courses and projects on Machine Learning and Artificial Intelligence that I have cleared and might be helpful for anyone hoping to improve their skills and grow their experience.

theme: jekyll-theme-cayman